version: "3.3"
services:
  spark-master:
    image: spark-master:2.3.1
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/apps:/opt/spark-apps
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/master:/opt/spark-data
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/submit:/opt/spark-submit
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker-1:
    image: spark-worker:2.3.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.3
    volumes:
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/apps:/opt/spark-apps
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/data1:/opt/spark-data
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/submit:/opt/spark-submit
  spark-worker-2:
    image: spark-worker:2.3.1
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.4
    volumes:
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/apps:/opt/spark-apps
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/data2:/opt/spark-data
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/submit:/opt/spark-submit
  spark-worker-3:
    image: spark-worker:2.3.1
    container_name: spark-worker-3
    hostname: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-3"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.5
    volumes:
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/apps:/opt/spark-apps
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/data3:/opt/spark-data
       - /home/jkondapalli/Documents/tenable/git/jkondapalli/docker-spark-cluster/submit:/opt/spark-submit
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16